/*
CREATE DATABASE Sigeat
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE Sigeat;

CREATE TABLE Clientes (
Id INT PRIMARY KEY AUTO_INCREMENT,
Nome VARCHAR(80) NOT NULL,
Endereco VARCHAR(150) NOT NULL,
Telefone VARCHAR(15) NOT NULL,
Email VARCHAR(50)
)DEFAULT CHARSET = utf8;

SELECT * FROM Clientes;

CREATE TABLE OS (
Nmr_OS INT PRIMARY KEY AUTO_INCREMENT,
Data_OS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Tipo VARCHAR(15),
Situacao VARCHAR(25),
Equipamento VARCHAR(50) NOT NULL,
Defeito VARCHAR(100) NOT NULL,
Observacao VARCHAR(100),
Servico VARCHAR(100),
Tecnico VARCHAR(50),
Valor DECIMAL(10, 2),
Id_Cliente INT NOT NULL,
FOREIGN KEY(Id_Cliente) REFERENCES Clientes(Id)
)DEFAULT CHARSET = utf8;

SELECT * FROM OS;

CREATE TABLE Usuarios (
Id INT PRIMARY KEY AUTO_INCREMENT,
Nome VARCHAR(80) NOT NULL,
Login VARCHAR(15) NOT NULL,
Senha VARCHAR(15) NOT NULL,
Perfil VARCHAR(20)
)DEFAULT CHARSET = utf8;

SELECT * FROM OS;
*/