/*
 * Formulário responsável por exibir os atalhos do SIGEAT
 */
package com.sigeat.app;

/*
 * SIGEAT/ Application / Atalhos de Teclado
 * @author Junior
 * Version : 1.0.0
 */
public class FrmCartaoAtalhos extends javax.swing.JDialog {

    /**
     * Creates new form FrmAtalhos
     */
    public FrmCartaoAtalhos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFundo = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panAtalhos = new javax.swing.JPanel();
        panTitle = new javax.swing.JLabel();
        lblAta11 = new javax.swing.JLabel();
        lblUser10 = new javax.swing.JLabel();
        panPan4 = new javax.swing.JPanel();
        lblAta12 = new javax.swing.JLabel();
        lblUser11 = new javax.swing.JLabel();
        lblUser12 = new javax.swing.JLabel();
        lblAta13 = new javax.swing.JLabel();
        panPan6 = new javax.swing.JPanel();
        lblAta15 = new javax.swing.JLabel();
        lblUser14 = new javax.swing.JLabel();
        lblAta16 = new javax.swing.JLabel();
        lblUser15 = new javax.swing.JLabel();
        lblAta18 = new javax.swing.JLabel();
        lblUser17 = new javax.swing.JLabel();
        panPan7 = new javax.swing.JPanel();
        lblAta17 = new javax.swing.JLabel();
        lblUser16 = new javax.swing.JLabel();
        panPan8 = new javax.swing.JPanel();
        lblAta19 = new javax.swing.JLabel();
        lblUser18 = new javax.swing.JLabel();
        lblAta20 = new javax.swing.JLabel();
        lblUser19 = new javax.swing.JLabel();
        panPan9 = new javax.swing.JPanel();
        lblAta21 = new javax.swing.JLabel();
        lblUser20 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cartão de Atalhos de Teclado");
        setResizable(false);

        panFundo.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 153));
        lblTitle.setText("Atalhos do SIGEAT");

        panAtalhos.setBackground(new java.awt.Color(255, 255, 255));
        panAtalhos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panAtalhos.setPreferredSize(new java.awt.Dimension(283, 121));

        panTitle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        panTitle.setForeground(new java.awt.Color(255, 102, 0));
        panTitle.setText("Atalhos");

        lblAta11.setText("alt- I");

        lblUser10.setText("Novo usuário");

        lblAta12.setText("alt- U");

        lblUser11.setText("Pesquisar usuário");

        javax.swing.GroupLayout panPan4Layout = new javax.swing.GroupLayout(panPan4);
        panPan4.setLayout(panPan4Layout);
        panPan4Layout.setHorizontalGroup(
            panPan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPan4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblAta12)
                .addGap(30, 30, 30)
                .addComponent(lblUser11, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panPan4Layout.setVerticalGroup(
            panPan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblAta12)
                .addComponent(lblUser11))
        );

        lblUser12.setText("Novo cliente");

        lblAta13.setText("alt- V");

        lblAta15.setText("alt- C");

        lblUser14.setText("Pesquisar cliente");

        javax.swing.GroupLayout panPan6Layout = new javax.swing.GroupLayout(panPan6);
        panPan6.setLayout(panPan6Layout);
        panPan6Layout.setHorizontalGroup(
            panPan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPan6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblAta15)
                .addGap(32, 32, 32)
                .addComponent(lblUser14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panPan6Layout.setVerticalGroup(
            panPan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblUser14)
                .addComponent(lblAta15))
        );

        lblAta16.setText("alt- O");

        lblUser15.setText("OS");

        lblAta18.setText("alt- A");

        lblUser17.setText("Calendário");

        lblAta17.setText("alt- Q");

        lblUser16.setText("Calculadora");

        javax.swing.GroupLayout panPan7Layout = new javax.swing.GroupLayout(panPan7);
        panPan7.setLayout(panPan7Layout);
        panPan7Layout.setHorizontalGroup(
            panPan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPan7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblAta17)
                .addGap(29, 29, 29)
                .addComponent(lblUser16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panPan7Layout.setVerticalGroup(
            panPan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblUser16)
                .addComponent(lblAta17))
        );

        lblAta19.setText("alt- S");

        lblUser18.setText("Sobre");

        javax.swing.GroupLayout panPan8Layout = new javax.swing.GroupLayout(panPan8);
        panPan8.setLayout(panPan8Layout);
        panPan8Layout.setHorizontalGroup(
            panPan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPan8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblAta19)
                .addGap(32, 32, 32)
                .addComponent(lblUser18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panPan8Layout.setVerticalGroup(
            panPan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblUser18)
                .addComponent(lblAta19))
        );

        lblAta20.setText("alt- T");

        lblUser19.setText("Atalhos de teclado");

        lblAta21.setText("alt- F4");

        lblUser20.setText("Sair");

        javax.swing.GroupLayout panPan9Layout = new javax.swing.GroupLayout(panPan9);
        panPan9.setLayout(panPan9Layout);
        panPan9Layout.setHorizontalGroup(
            panPan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPan9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblAta21)
                .addGap(28, 28, 28)
                .addComponent(lblUser20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panPan9Layout.setVerticalGroup(
            panPan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblUser20)
                .addComponent(lblAta21))
        );

        javax.swing.GroupLayout panAtalhosLayout = new javax.swing.GroupLayout(panAtalhos);
        panAtalhos.setLayout(panAtalhosLayout);
        panAtalhosLayout.setHorizontalGroup(
            panAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPan6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAtalhosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panPan7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panPan8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panAtalhosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAtalhosLayout.createSequentialGroup()
                        .addComponent(lblAta16)
                        .addGap(32, 32, 32)
                        .addComponent(lblUser15))
                    .addGroup(panAtalhosLayout.createSequentialGroup()
                        .addGroup(panAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAta11)
                            .addComponent(lblAta13))
                        .addGap(33, 33, 33)
                        .addGroup(panAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser12)
                            .addComponent(lblUser10)))
                    .addGroup(panAtalhosLayout.createSequentialGroup()
                        .addComponent(lblAta18)
                        .addGap(32, 32, 32)
                        .addComponent(lblUser17))
                    .addGroup(panAtalhosLayout.createSequentialGroup()
                        .addComponent(lblAta20)
                        .addGap(32, 32, 32)
                        .addComponent(lblUser19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panPan9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panAtalhosLayout.createSequentialGroup()
                .addComponent(panPan4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panAtalhosLayout.setVerticalGroup(
            panAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAtalhosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser10)
                    .addComponent(lblAta11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPan4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAta13)
                    .addComponent(lblUser12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPan6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser15)
                    .addComponent(lblAta16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPan7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser17)
                    .addComponent(lblAta18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPan8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panAtalhosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser19)
                    .addComponent(lblAta20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPan9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnFechar.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setToolTipText("Fechar");
        btnFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFundoLayout = new javax.swing.GroupLayout(panFundo);
        panFundo.setLayout(panFundoLayout);
        panFundoLayout.setHorizontalGroup(
            panFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFundoLayout.createSequentialGroup()
                .addGroup(panFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFundoLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblTitle))
                    .addGroup(panFundoLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(panAtalhos, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panFundoLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        panFundoLayout.setVerticalGroup(
            panFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panAtalhos, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCartaoAtalhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCartaoAtalhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCartaoAtalhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCartaoAtalhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCartaoAtalhos dialog = new FrmCartaoAtalhos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel lblAta11;
    private javax.swing.JLabel lblAta12;
    private javax.swing.JLabel lblAta13;
    private javax.swing.JLabel lblAta15;
    private javax.swing.JLabel lblAta16;
    private javax.swing.JLabel lblAta17;
    private javax.swing.JLabel lblAta18;
    private javax.swing.JLabel lblAta19;
    private javax.swing.JLabel lblAta20;
    private javax.swing.JLabel lblAta21;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser10;
    private javax.swing.JLabel lblUser11;
    private javax.swing.JLabel lblUser12;
    private javax.swing.JLabel lblUser14;
    private javax.swing.JLabel lblUser15;
    private javax.swing.JLabel lblUser16;
    private javax.swing.JLabel lblUser17;
    private javax.swing.JLabel lblUser18;
    private javax.swing.JLabel lblUser19;
    private javax.swing.JLabel lblUser20;
    private javax.swing.JPanel panAtalhos;
    private javax.swing.JPanel panFundo;
    private javax.swing.JPanel panPan4;
    private javax.swing.JPanel panPan6;
    private javax.swing.JPanel panPan7;
    private javax.swing.JPanel panPan8;
    private javax.swing.JPanel panPan9;
    private javax.swing.JLabel panTitle;
    // End of variables declaration//GEN-END:variables
}
